### ISSUE TITLE
Repress returns undefined on posts

### ISSUE THREAD

**Issue by Sintifo** [humanmade/repress#20]
Hey,
I've just started to use repress to get the posts from our website and display them with react.
My problem is that I followed the tutorial 1:1 and still all posts and archives return undefined in the Component withSingle() and withArchive().
Although the store contains the post / archive with correct ID.

Completely stuck here and wondering if I made a typo or there's a small problem in the tutorial.
```
// Post.tsx
import {withSingle} from '@humanmade/repress';
import * as React from 'react';
import {posts} from "../types";

const Post = (props) => <article>
    <h3>{props.post.title}</h3>
</article>;

export default withSingle(
    posts,
    state => state.posts,

    props => props.id
)(Post);
``` 
```
// types.tsx
import {handler} from '@humanmade/repress';
import {config} from './config';

export const posts = new handler({
    type: 'posts',
    url: config.api.url + 'wp-json/wp/v2/posts'
});

posts.registerArchive( 'home', {} );
posts.registerArchive( 'stickied', { sticky: '1' } );

``` 
Returns TypeError: props.post is undefined.

Thanks for your help in advance!

**Comment by rmccue** [comment]
Hi, sorry for not getting back to you earlier!

`post` will be `null` until it's loaded, so you need to make sure that you're also checking that:
```jsx
const Post = (props) => <article>
    {props.loading ? (
        <p>Loading…</p>
    ) : (
        <h3>{props.post.title}</h3>
    )}
</article>;
```

Note that if `loading` is `false`, `post` may still be `null` if the post could not be loaded. You can use this to write an error handler:
```jsx
const Post = (props) => <article>
    {props.loading ? (
        <p>Loading…</p>
    ) : (
        ! props.post ? (
            <p>Could not load post</p>
        ) : (
            <h3>{props.post.title}</h3>
        )
    )}
</article>;
```

(Parentheses added here for clarity, but not required)

**Comment by Sintifo** [comment]
Thanks for the clarification!
Figured part of it out by trial and error.

It may be wise to include this in the getting started tutorial. Some of the examples do not check for loading posts. 
If I have time I make a PR to fix this.
